export const sportPatterns = {
  outdoor_running: { color: "#35d1c5", label: "Running" },
  outdoor_walking: { color: "#00d4ff", label: "Walking" },
  aerobics: { color: "#ff0080", label: "Aerobics" },
  mixed_aerobics: { color: "#ff3399", label: "Mixed Aerobics" },
  yoga: { color: "#9d4edd", label: "Yoga" },
  free_training: { color: "#06ffa5", label: "Free Training" },
  upper_limb_training: { color: "#ffbe0b", label: "Upper Body" },
  lower_limb_training: { color: "#fb5607", label: "Lower Body" },
  core_training: { color: "#ff006e", label: "Core" },
  physical_training: { color: "#8338ec", label: "Physical" },
  pilates: { color: "#c77dff", label: "Pilates" },
  flexibility_training: { color: "#e0aaff", label: "Flexibility" },
  indoor_walking: { color: "#48cae4", label: "Indoor Walking" },
  indoor_riding: { color: "#0096c7", label: "Indoor Cycling" },
  weight_lifting: { color: "#ff9500", label: "Weight Lifting" },
  waist_training: { color: "#ff6b6b", label: "Waist" },
  back_training: { color: "#ffd166", label: "Back" },
  high_interval_training: { color: "#ef233c", label: "HIIT" },
};
