export const sportPatterns = {
  outdoor_running: {
    freq: 0.8,
    amp: 1.2,
    pattern: "sharp",
    color: "#35d1c5",
    label: "Running",
  },
  outdoor_walking: {
    freq: 0.5,
    amp: 0.6,
    pattern: "smooth",
    color: "#00d4ff",
    label: "Walking",
  },
  aerobics: {
    freq: 1.0,
    amp: 1.3,
    pattern: "sharp",
    color: "#ff0080",
    label: "Aerobics",
  },
  mixed_aerobics: {
    freq: 0.9,
    amp: 1.1,
    pattern: "sharp",
    color: "#ff3399",
    label: "Mixed Aerobics",
  },
  yoga: {
    freq: 0.3,
    amp: 0.4,
    pattern: "smooth",
    color: "#9d4edd",
    label: "Yoga",
  },
  free_training: {
    freq: 0.7,
    amp: 0.9,
    pattern: "moderate",
    color: "#06ffa5",
    label: "Free Training",
  },
  upper_limb_training: {
    freq: 0.6,
    amp: 0.8,
    pattern: "moderate",
    color: "#ffbe0b",
    label: "Upper Body",
  },
  lower_limb_training: {
    freq: 0.6,
    amp: 0.8,
    pattern: "moderate",
    color: "#fb5607",
    label: "Lower Body",
  },
  core_training: {
    freq: 0.6,
    amp: 0.7,
    pattern: "moderate",
    color: "#ff006e",
    label: "Core",
  },
  physical_training: {
    freq: 0.7,
    amp: 0.9,
    pattern: "moderate",
    color: "#8338ec",
    label: "Physical",
  },
  pilates: {
    freq: 0.4,
    amp: 0.5,
    pattern: "smooth",
    color: "#c77dff",
    label: "Pilates",
  },
  flexibility_training: {
    freq: 0.3,
    amp: 0.4,
    pattern: "smooth",
    color: "#e0aaff",
    label: "Flexibility",
  },
  indoor_walking: {
    freq: 0.5,
    amp: 0.6,
    pattern: "smooth",
    color: "#48cae4",
    label: "Indoor Walking",
  },
  indoor_riding: {
    freq: 0.8,
    amp: 1.0,
    pattern: "sharp",
    color: "#0096c7",
    label: "Indoor Cycling",
  },
  weight_lifting: {
    freq: 0.5,
    amp: 1.0,
    pattern: "moderate",
    color: "#ff9500",
    label: "Weight Lifting",
  },
  waist_training: {
    freq: 0.6,
    amp: 0.7,
    pattern: "moderate",
    color: "#ff6b6b",
    label: "Waist",
  },
  back_training: {
    freq: 0.6,
    amp: 0.8,
    pattern: "moderate",
    color: "#ffd166",
    label: "Back",
  },
  high_interval_training: {
    freq: 1.2,
    amp: 1.4,
    pattern: "sharp",
    color: "#ef233c",
    label: "HIIT",
  },
  rope_skipping: {
    freq: 1.0,
    amp: 1.2,
    pattern: "sharp",
    color: "#d90429",
    label: "Rope Skipping",
  },
};
